name = "FourierFilterFlux"
uuid = "3d7dfd45-6c90-4c9b-b697-194a05757159"
version = "0.3.5"
authors = ["dsweber2"]

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.10"
cuDNN = "1.4.6"

[targets]
test = ["Test", "FFTW", "LinearAlgebra", "Logging", "Zygote", "Documenter", "LuxCUDA"]
